# BÀI TẬP: MEDICAL INSURANCE COST
**Nguồn:** kaggle.com/datasets/mosapabdelghany/medical-insurance-cost-dataset

## Setup

In [1]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')


csv_path = 'https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv'

df = pd.read_csv(csv_path)
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [2]:
# TODO
# DATA SIZE
df.shape

(1338, 7)

In [3]:
# column names
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [5]:
df.columns.to_list()

['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges']

In [7]:
# data types
df.dtypes

age           int64
sex          object
bmi         float64
children      int64
smoker       object
region       object
charges     float64
dtype: object

## A.2. Missing values & Duplicate data

In [8]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [12]:
# TODO
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1333    False
1334    False
1335    False
1336    False
1337    False
Length: 1338, dtype: bool

In [13]:
df.duplicated

<bound method DataFrame.duplicated of       age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]>

## A.3. Invalid values

In [23]:
# Kiểm tra tuổi < 20 hoặc quá cao
invalid_age = df[(df['age'] < 20) | (df['age'] > 100)]
print(invalid_age)

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
15     19    male  24.600         1     no  southwest   1837.23700
22     18    male  34.100         0     no  southeast   1137.01100
31     18  female  26.315         0     no  northeast   2198.18985
...   ...     ...     ...       ...    ...        ...          ...
1315   18    male  28.310         1     no  northeast  11272.33139
1316   19  female  20.600         0     no  southwest   1731.67700
1317   18    male  53.130         0     no  southeast   1163.46270
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350

[137 rows x 7 columns]

In [26]:
# TODO
# Kiểm tra BMI < 10 hoặc > 60 
invalid_bmi = df[(df['bmi'] < 10) | (df['bmi'] > 60)]
print(invalid_bmi)

Empty DataFrame
Columns: [age, sex, bmi, children, smoker, region, charges]
Index: []

## A.4. Create a new column
Tạo cột `bmi_group`: Normal (<25), Overweight (25-30), Obese (>=30).

In [ ]:
# TODO
def bmi_category(bmi):
    if bmi < 25:
        return 'Normal'
    elif bmi < 30:
        return 'Overweight'
    else:
        return 'Obese'
df['bmi_group'] = df['bmi'].apply(bmi_category)
df['bmi_group'].value_counts()

bmi_group
Obese         707
Overweight    386
Normal        245
Name: count, dtype: int64

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [ ]:
# TODO
mean_charges= df['charges'].mean()
print('Mean charges:', mean_charges)

# mode_charges = df['charges'].mode()[0]

Mean charges: 13270.422265141257

In [37]:
df.describe()

               age          bmi     children       charges  mean_charges
count  1338.000000  1338.000000  1338.000000   1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265  13270.422265
std      14.049960     6.098187     1.205493  12110.011237      0.000000
min      18.000000    15.960000     0.000000   1121.873900  13270.422265
25%      27.000000    26.296250     0.000000   4740.287150  13270.422265
50%      39.000000    30.400000     1.000000   9382.033000  13270.422265
75%      51.000000    34.693750     2.000000  16639.912515  13270.422265
max      64.000000    53.130000     5.000000  63770.428010  13270.422265

In [35]:
median_charges = df['charges'].median()
print('Median charges:', median_charges)

Median charges: 9382.033

In [36]:
mode_charges = df['charges'].mode()[0]
print('Mode charges:', mode_charges)

Mode charges: 1639.5631

## Group 2 — Dispersion

In [38]:
# TODO

var_charges = df['charges'].var()
std_charges = df['charges'].std()

range_charges = df['charges'].max() - df['charges'].min()

print("Variance:", var_charges)
print("Standard Deviation:", std_charges)
print("Range:", range_charges)

Variance: 146652372.15285498
Standard Deviation: 12110.011236694001
Range: 62648.554110000005

## Group 3 — Location and Shape

In [39]:
# TODO
quantiles = df['charges'].quantile([0.25, 0.5, 0.75])

skewness = df['charges'].skew()
kurtosis = df['charges'].kurtosis()

print("Quantiles:\n", quantiles)
print("Skewness:", skewness)
print("Kurtosis:", kurtosis)

Quantiles:
 0.25     4740.287150
0.50     9382.033000
0.75    16639.912515
Name: charges, dtype: float64
Skewness: 1.5158796580240388
Kurtosis: 1.6062986532967907

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Người hút thuốc trả chi phí cao hơn bao nhiêu lần so với người không hút, và có đồng đều giữa các vùng không?

In [41]:
# TODO
# Trung bình charges theo smoker
df.groupby('smoker')['charges'].mean()

# Trung bình charges theo smoker và region
df.groupby(['smoker','region'])['charges'].mean()

smoker  region
no      northeast     9165.531672
        northwest     8556.463715
        southeast     8032.216309
        southwest     8019.284513
yes     northeast    29673.536473
        northwest    30192.003182
        southeast    34844.996824
        southwest    32269.063494
Name: charges, dtype: float64

## Câu hỏi 2: BMI có tương quan với chi phí mạnh hơn ở nhóm hút thuốc hay không hút thuốc?

In [42]:
# TODO
# tương quan Pearson giữa BMI và charges theo nhóm smoker
df.groupby('smoker').apply(lambda g: g['bmi'].corr(g['charges']))

C:\Users\LAPTOP\AppData\Local\Temp\ipykernel_13968\929697595.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('smoker').apply(lambda g: g['bmi'].corr(g['charges']))

smoker
no     0.084037
yes    0.806481
dtype: float64

## Câu hỏi 3: Vùng nào có chi phí bảo hiểm trung bình cao nhất?

In [43]:
# TODO
df.groupby('region')['charges'].mean().sort_values(ascending=False)

region
southeast    14735.411438
northeast    13406.384516
northwest    12417.575374
southwest    12346.937377
Name: charges, dtype: float64

## Câu hỏi 4: Số lượng con cái có làm tăng chi phí bảo hiểm không?

In [46]:
# TODO
df.groupby('children')['charges'].mean()

children
0    12365.975602
1    12731.171832
2    15073.563734
3    15355.318367
4    13850.656311
5     8786.035247
Name: charges, dtype: float64

## Câu hỏi 5: Tuổi có tương quan với chi phí bảo hiểm không?

In [ ]:
# TODO

df['age'].corr(df['charges'])

np.float64(0.29900819333064776)

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể.

-Người hút thuốc trả chi phí cao gấp nhiều lần người không hút, và sự khác biệt này rõ rệt ở tất cả các vùng.
-BMI có ảnh hưởng mạnh hơn đến chi phí ở nhóm hút thuốc.
-Vùng southeast thường có chi phí trung bình cao nhất.
-Số lượng con cái không làm tăng chi phí rõ rệt.
-Tuổi có tương quan dương với chi phí, nghĩa là càng lớn tuổi thì chi phí bảo hiểm càng cao.